version: "2"
services:

##### ELK services
  elasticsearch:
    image: elasticsearch:2.4.1
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
      - "5001:5001"
    links:
      - elasticsearch
  kibana:
    build: ./kibana
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    environment:
      VIRTUAL_HOST: '*/'
    ports:
      - "5601:5601"
    links:
      - elasticsearch

## ZK
  zk:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5001"
    depends_on:
      - logstash

## KAFKA
  kafka:
    image: wurstmeister/kafka:0.9.0.0-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ''
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_DELETE_RETENTION_MS: 1000
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    depends_on:
      - zk
      - logstash
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5001"

## KAFKA-MANAGER
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zk:2181
      APPLICATION_SECRET: letmein
    depends_on:
      - kafka
      - logstash
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5001"



## MARATHON
  master:
    image: mesosphere/mesos-master:1.0.1-2.0.93.ubuntu1404
    network_mode: host
    environment:
      MESOS_ZK: zk://127.0.0.1:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
      MESOS_REGISTRY: replicated_log # default is in_memory for some reason
      MESOS_HOSTNAME: 127.0.0.1
      LIBPROCESS_IP: 127.0.0.1
    depends_on:
      - zk

  slave-one:
    image: mesosphere/mesos-slave:1.0.1-2.0.93.ubuntu1404
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_HOSTNAME: 127.0.0.1
      LIBPROCESS_IP: 127.0.0.1
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk


  marathon:
    image: mesosphere/marathon:v1.3.0
    network_mode: host
    environment:
      MARATHON_MASTER: zk://127.0.0.1:2181/mesos
    depends_on:
      - zk


#### GERRIT
  gerrit:
    image: gerrit
    ports:
        - 8022:8080
        - 29418:29418
    environment:
      ZK_GERRIT_CONFIG: zk://zk:2181/nestor/config/dev/gerrit/gerrit.config
      ZK_SECURE_CONFIG: zk://zk:2181/nestor/config/dev/gerrit/secure.config
      SERVICE_PORTS: 8080
      TCP_PORTS: ''
      VIRTUAL_HOST: '*/gerrit/*'
    volumes:
      - ${HOME}/gerrit:/var/gerrit/review_site
    links:
        - zk
        - kafka
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5001"

#### BUILDBOT_TRAVIS
  bbtravis:
    image: bbtravis
    ports:
        - 8010:8010
        - 9989:9989
    links:
        - zk
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5001"

  lb:
    image: dockercloud/haproxy
    links:
      - gerrit
      - kibana
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
